//! Interface-discovery / metadata layer ported (or documented) from
//! `akshare/registry.py`.
//!
//! ## DEFERRED — akshare-internal metadata, not a market-data API
//!
//! These three functions are a search/index layer over akshare's *bundled*
//! `interfaces.json` registry (generated by `scripts/build_registry.py` and
//! shipped inside the akshare package). They perform no network I/O and return
//! akshare's own API catalog — they are not Chinese-market-data endpoints and
//! have no meaningful standalone port. Recorded here (and in
//! `docs/MAPPING.md`) for completeness.
//!
//! * `interface_info(name)` (`registry.py:215`) — deep-copy of one interface's
//!   metadata record from the bundled registry.
//! * `list_categories()` (`registry.py:232`) — category → interface-count
//!   aggregation over the bundled registry.
//! * `search(query, ...)` (`registry.py:175`) — token/bigram-scored ranking
//!   over the bundled registry.
//!
//! If a local interface catalog is ever needed, the faithful port would embed
//! a generated `interfaces.json` and re-implement the scoring in `search` —
//! out of scope for the data-layer port.
