// Wave-3 port of akshare `stock_feature` (indicators / board / 沪深港通 / 融资融券 / 研报 / 龙虎榜 / 涨停池).
// Each leaf module is filled by an independent agent; do not edit this file.
pub mod indicators_a;
pub mod indicators_b;
pub mod margin_research;
pub mod board_zt;

pub mod wv_sf_misc1;

pub mod wv_sf_misc2;

pub mod wv_sf_misc3;

pub mod wv_sf_sgt;

pub mod wv_sf_more;

pub mod sf_gaps;
pub mod excel_gaps;
pub mod stock_feature_html_gaps;
