//! Eastmoney datacenter-web macro indicators for China (port of the 25 lowest-risk
//! `datacenter-web.eastmoney.com/api/data/v1/get` functions from
//! `akshare/economic/macro_china.py`).
//!
//! All 25 functions below are PURE HTTP: a single `GET` to the Eastmoney
//! datacenter JSON API (no JS / token / signature / `execjs` / cookie). They split
//! into two shapes:
//!
//! * **Group A — `RPT_INDUSTRY_INDEX`** (16 fns): one reportName, filtered by
//!   `INDICATOR_ID`, always returning the same 8-column layout
//!   (`REPORT_DATE`, `INDICATOR_VALUE`, `CHANGE_RATE`, `CHANGERATE_3M/6M/1Y/2Y/3Y`).
//!   A single [`IndustryIndexRow`] struct and [`parse_industry_index`] parser serve
//!   every one; the per-fn `pub async fn`s are generated by the `industry_index!`
//!   macro.
//! * **Group B — `RPT_ECONOMY_*`** (9 fns): each has its own `reportName` + `columns`
//!   and its own output column layout, so each gets a dedicated `Row` struct and
//!   `parse_*` parser sharing the [`emdc_fetch`] helper.
//!
//! ## Ported functions
//!
//! | Rust fn | akshare line | reportName / indicator |
//! | --- | --- | --- |
//! | `macro_china_bank_financing` | macro_china.py:1241 | RPT_INDUSTRY_INDEX / EMI01516267 |
//! | `macro_china_insurance_income` | macro_china.py:1287 | RPT_INDUSTRY_INDEX / EMM00088870 |
//! | `macro_china_mobile_number` | macro_china.py:1333 | RPT_INDUSTRY_INDEX / EMI00225823 |
//! | `macro_china_vegetable_basket` | macro_china.py:1380 | RPT_INDUSTRY_INDEX / EMI00009275 |
//! | `macro_china_agricultural_product` | macro_china.py:1435 | RPT_INDUSTRY_INDEX / EMI00009274 |
//! | `macro_china_agricultural_index` | macro_china.py:1490 | RPT_INDUSTRY_INDEX / EMI00662543 |
//! | `macro_china_energy_index` | macro_china.py:1545 | RPT_INDUSTRY_INDEX / EMI00662539 |
//! | `macro_china_commodity_price_index` | macro_china.py:1600 | RPT_INDUSTRY_INDEX / EMI00662535 |
//! | `macro_global_sox_index` | macro_china.py:1655 | RPT_INDUSTRY_INDEX / EMI00055562 |
//! | `macro_china_yw_electronic_index` | macro_china.py:1710 | RPT_INDUSTRY_INDEX / EMI00055551 |
//! | `macro_china_construction_index` | macro_china.py:1765 | RPT_INDUSTRY_INDEX / EMI00662541 |
//! | `macro_china_construction_price_index` | macro_china.py:1823 | RPT_INDUSTRY_INDEX / EMI00237146 |
//! | `macro_china_lpi_index` | macro_china.py:1878 | RPT_INDUSTRY_INDEX / EMI00352262 |
//! | `macro_china_bdti_index` | macro_china.py:1933 | RPT_INDUSTRY_INDEX / EMI00107668 |
//! | `macro_china_bsi_index` | macro_china.py:1988 | RPT_INDUSTRY_INDEX / EMI00107667 |
//! | `macro_china_real_estate` | macro_china.py:3699 | RPT_INDUSTRY_INDEX / EMM00121987 |
//! | `macro_china_new_financial_credit` | macro_china.py:2142 | RPT_ECONOMY_RMB_LOAN |
//! | `macro_china_fx_gold` | macro_china.py:2190 | RPT_ECONOMY_GOLD_CURRENCY |
//! | `macro_china_stock_market_cap` | macro_china.py:2256 | RPT_ECONOMY_STOCK_STATISTICS |
//! | `macro_china_hgjck` | macro_china.py:2723 | RPT_ECONOMY_CUSTOMS |
//! | `macro_china_czsr` | macro_china.py:2814 | RPT_ECONOMY_INCOME |
//! | `macro_china_whxd` | macro_china.py:2867 | RPT_ECONOMY_FOREX_LOAN |
//! | `macro_china_wbck` | macro_china.py:2917 | RPT_ECONOMY_FOREX_DEPOSIT |
//! | `macro_china_xfzxx` | macro_china.py:2966 | RPT_ECONOMY_FAITH_INDEX |
//! | `macro_china_reserve_requirement_ratio` | macro_china.py:3096 | RPT_ECONOMY_DEPOSIT_RESERVE |
//!
//! ## DEFERRED (not ported)
//!
//! These functions exist in `akshare/economic/macro_china.py` but are **skipped**:
//!
//! * **Jin10 `reportType` token-gated** (`datacenter-api.jin10.com`, requires an
//!   `x-csrf-token`): `macro_china_gdp_yearly`, `macro_china_gdp_monthly`,
//!   `macro_china_cpi_yearly`, `macro_china_cpi_monthly`, `macro_china_ppi_yearly`,
//!   `macro_china_cx_pmi_yearly`, `macro_china_pmi_yearly`, `macro_china_non_man_pmi`,
//!   `macro_china_fx_reserves_yearly`, `macro_china_m2_yearly`, `macro_china_m1_yearly`,
//!   `macro_china_m0_yearly`, `macro_china_exports_yoy`, `macro_china_imports_yoy`,
//!   `macro_china_trade_balance`, `macro_china_industrial_production_yoy`,
//!   `macro_china_social_consumption_yoy`, `macro_china_fx_reserves_monthly`,
//!   `macro_china_new_house_price`, `macro_china_rmb`, `macro_china_shibor_all`,
//!   `macro_china_hk_market_info`, `macro_china_daily_energy`, `macro_china_au_report`,
//!   `macro_china_market_margin_sh`, `macro_china_market_margin_sz`, etc.
//!   (each marked `/// DEFERRED: jin10 reportType token-gated` in the source).
//! * **Sina `MacPage_Service.get_pagedata`** (HTML/JS-rendered, ~10 fns such as
//!   `macro_china_qyspjg`, `macro_china_fdi`, `macro_china_shrzgm`,
//!   `macro_china_urban_unemployment`, `macro_china_enterprise_boom_index`,
//!   `macro_china_national_tax_receipts`, `macro_china_gyzjz`,
//!   `macro_china_consumer_goods_retail`, `macro_china_new_financial_credit` shipper
//!   indices `macro_shipping_bci/bdi/bpi/bcti`, etc.).
//! * **Already ported elsewhere** (skip to avoid duplication): `macro_china_gdp`,
//!   `macro_china_cpi`, `macro_china_money_supply`, `macro_china_ppi`
//!   (in `src/economic/china.rs`).

use serde_json::Value;

use crate::core::client::Client;
use crate::core::error::{Error, Result};

const SOURCE_EASTMONEY: &str = "eastmoney";
const BASE: &str = "https://datacenter-web.eastmoney.com/api/data/v1/get";

/// Extract `result.data` (the row array) from a datacenter-web response.
fn emg_data_array(resp: &Value) -> Result<&Vec<Value>> {
    resp.get("result")
        .and_then(|r| r.get("data"))
        .and_then(|d| d.as_array())
        .ok_or_else(|| Error::UpstreamChanged {
            origin: SOURCE_EASTMONEY,
            message: "missing result.data".into(),
        })
}

fn fstr(item: &Value, k: &str) -> Option<String> {
    item.get(k).and_then(|v| v.as_str()).map(|s| s.to_string())
}

fn fnum(item: &Value, k: &str) -> Option<f64> {
    item.get(k).and_then(|v| match v {
        Value::Number(n) => n.as_f64(),
        Value::String(s) => s.trim().parse::<f64>().ok(),
        _ => None,
    })
}

/// Shared fetch for every datacenter-web indicator in this module.
///
/// Builds the standard Eastmoney `RPT_*` request (optionally filtered by
/// `INDICATOR_ID`), returns the raw `result.data` row array for the caller's
/// `parse_*` function to turn into typed rows.
#[allow(clippy::too_many_arguments)]
async fn emdc_fetch(
    client: &Client,
    fn_name: &'static str,
    report_name: &str,
    columns: &str,
    page_size: &str,
    sort_columns: &str,
    sort_types: &str,
    filter: Option<&str>,
) -> Result<Vec<Value>> {
    let mut params: Vec<(&str, &str)> = vec![
        ("reportName", report_name),
        ("columns", columns),
        ("pageNumber", "1"),
        ("pageSize", page_size),
        ("sortColumns", sort_columns),
        ("sortTypes", sort_types),
        ("source", "WEB"),
        ("client", "WEB"),
        ("p", "1"),
        ("pageNo", "1"),
        ("pageNum", "1"),
    ];
    if let Some(f) = filter {
        params.push(("filter", f));
    }
    let v = client
        .get_json(SOURCE_EASTMONEY, fn_name, BASE, &params)
        .await?;
    emg_data_array(&v).cloned()
}

// ===========================================================================
// Group A — RPT_INDUSTRY_INDEX (single shared shape, filtered by INDICATOR_ID)
// ===========================================================================

/// A single observation of an Eastmoney `RPT_INDUSTRY_INDEX` indicator.
///
/// Mirrors the 8 columns every `RPT_INDUSTRY_INDEX` row exposes:
/// `REPORT_DATE` (日期), `INDICATOR_VALUE` (最新值), `CHANGE_RATE` (涨跌幅) and
/// the rolling `CHANGERATE_3M/6M/1Y/2Y/3Y` (近3月/6月/1年/2年/3年涨跌幅).
#[derive(Debug, Clone, serde::Serialize)]
pub struct IndustryIndexRow {
    /// 日期 (Eastmoney `REPORT_DATE`)
    pub date: String,
    /// 最新值 (Eastmoney `INDICATOR_VALUE`)
    pub latest_value: Option<f64>,
    /// 涨跌幅 (Eastmoney `CHANGE_RATE`)
    pub change_rate: Option<f64>,
    /// 近3月涨跌幅 (Eastmoney `CHANGERATE_3M`)
    pub change_3m: Option<f64>,
    /// 近6月涨跌幅 (Eastmoney `CHANGERATE_6M`)
    pub change_6m: Option<f64>,
    /// 近1年涨跌幅 (Eastmoney `CHANGERATE_1Y`)
    pub change_1y: Option<f64>,
    /// 近2年涨跌幅 (Eastmoney `CHANGERATE_2Y`)
    pub change_2y: Option<f64>,
    /// 近3年涨跌幅 (Eastmoney `CHANGERATE_3Y`)
    pub change_3y: Option<f64>,
}

/// Shared parser for every `RPT_INDUSTRY_INDEX` indicator response.
pub fn parse_industry_index(items: &[Value]) -> Result<Vec<IndustryIndexRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(date) = fstr(item, "REPORT_DATE") else {
            continue;
        };
        out.push(IndustryIndexRow {
            date,
            latest_value: fnum(item, "INDICATOR_VALUE"),
            change_rate: fnum(item, "CHANGE_RATE"),
            change_3m: fnum(item, "CHANGERATE_3M"),
            change_6m: fnum(item, "CHANGERATE_6M"),
            change_1y: fnum(item, "CHANGERATE_1Y"),
            change_2y: fnum(item, "CHANGERATE_2Y"),
            change_3y: fnum(item, "CHANGERATE_3Y"),
        });
    }
    Ok(out)
}

/// Generate a `pub async fn` per `RPT_INDUSTRY_INDEX` indicator.
macro_rules! industry_index {
    ($fn_name:ident, $doc:literal, $indicator_id:expr, $page_size:expr) => {
        #[doc = $doc]
        pub async fn $fn_name(client: &Client) -> Result<Vec<IndustryIndexRow>> {
            let filter = format!(r#"(INDICATOR_ID="{}")"#, $indicator_id);
            let data = emdc_fetch(
                client,
                stringify!($fn_name),
                "RPT_INDUSTRY_INDEX",
                "REPORT_DATE,INDICATOR_VALUE,CHANGE_RATE,CHANGERATE_3M,CHANGERATE_6M,CHANGERATE_1Y,CHANGERATE_2Y,CHANGERATE_3Y",
                $page_size,
                "REPORT_DATE",
                "-1",
                Some(filter.as_str()),
            )
            .await?;
            parse_industry_index(&data)
        }
    };
}

industry_index!(
    macro_china_bank_financing,
    "银行理财产品发行数量 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI01516267` (akshare/economic/macro_china.py:1241).",
    "EMI01516267",
    "1000"
);
industry_index!(
    macro_china_insurance_income,
    "原保险保费收入 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMM00088870` (akshare/economic/macro_china.py:1287).",
    "EMM00088870",
    "1000"
);
industry_index!(
    macro_china_mobile_number,
    "手机出货量 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00225823` (akshare/economic/macro_china.py:1333).",
    "EMI00225823",
    "1000"
);
industry_index!(
    macro_china_vegetable_basket,
    "菜篮子产品批发价格指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00009275` (akshare/economic/macro_china.py:1380).",
    "EMI00009275",
    "500"
);
industry_index!(
    macro_china_agricultural_product,
    "农产品批发价格总指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00009274` (akshare/economic/macro_china.py:1435).",
    "EMI00009274",
    "500"
);
industry_index!(
    macro_china_agricultural_index,
    "农副指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00662543` (akshare/economic/macro_china.py:1490).",
    "EMI00662543",
    "500"
);
industry_index!(
    macro_china_energy_index,
    "能源指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00662539` (akshare/economic/macro_china.py:1545).",
    "EMI00662539",
    "500"
);
industry_index!(
    macro_china_commodity_price_index,
    "大宗商品价格指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00662535` (akshare/economic/macro_china.py:1600).",
    "EMI00662535",
    "500"
);
industry_index!(
    macro_global_sox_index,
    "费城半导体指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00055562` (akshare/economic/macro_china.py:1655).",
    "EMI00055562",
    "500"
);
industry_index!(
    macro_china_yw_electronic_index,
    "义乌小商品指数-电子元器件 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00055551` (akshare/economic/macro_china.py:1710).",
    "EMI00055551",
    "500"
);
industry_index!(
    macro_china_construction_index,
    "建材指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00662541` (akshare/economic/macro_china.py:1765).",
    "EMI00662541",
    "500"
);
industry_index!(
    macro_china_construction_price_index,
    "建材价格指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00237146` (akshare/economic/macro_china.py:1823).",
    "EMI00237146",
    "500"
);
industry_index!(
    macro_china_lpi_index,
    "物流景气指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00352262` (akshare/economic/macro_china.py:1878).",
    "EMI00352262",
    "500"
);
industry_index!(
    macro_china_bdti_index,
    "原油运输指数(BDTI) — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00107668` (akshare/economic/macro_china.py:1933).",
    "EMI00107668",
    "500"
);
industry_index!(
    macro_china_bsi_index,
    "超灵便型船运价指数(BSI) — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMI00107667` (akshare/economic/macro_china.py:1988).",
    "EMI00107667",
    "500"
);
industry_index!(
    macro_china_real_estate,
    "国房景气指数 — Eastmoney `RPT_INDUSTRY_INDEX` indicator `EMM00121987` (akshare/economic/macro_china.py:3699).",
    "EMM00121987",
    "1000"
);

// ===========================================================================
// Group B — RPT_ECONOMY_* (each its own columns / output layout)
// ===========================================================================

/// 中国新增信贷数据 (`RPT_ECONOMY_RMB_LOAN`, macro_china.py:2142).
#[derive(Debug, Clone, serde::Serialize)]
pub struct NewFinancialCreditRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 当月 (Eastmoney `RMB_LOAN`)
    pub current: Option<f64>,
    /// 当月-同比增长 (Eastmoney `RMB_LOAN_SAME`)
    pub current_yoy: Option<f64>,
    /// 当月-环比增长 (Eastmoney `RMB_LOAN_SEQUENTIAL`)
    pub current_mom: Option<f64>,
    /// 累计 (Eastmoney `RMB_LOAN_ACCUMULATE`)
    pub accumulate: Option<f64>,
    /// 累计-同比增长 (Eastmoney `LOAN_ACCUMULATE_SAME`)
    pub accumulate_yoy: Option<f64>,
}

/// 东方财富-外汇和黄金储备 (`RPT_ECONOMY_GOLD_CURRENCY`, macro_china.py:2190).
#[derive(Debug, Clone, serde::Serialize)]
pub struct FxGoldRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 黄金储备-数值 (Eastmoney `GOLD_RESERVES`)
    pub gold_value: Option<f64>,
    /// 黄金储备-同比 (Eastmoney `GOLD_RESERVES_SAME`)
    pub gold_yoy: Option<f64>,
    /// 黄金储备-环比 (Eastmoney `GOLD_RESERVES_SEQUENTIAL`)
    pub gold_mom: Option<f64>,
    /// 国家外汇储备-数值 (Eastmoney `FOREX`)
    pub forex_value: Option<f64>,
    /// 国家外汇储备-同比 (Eastmoney `FOREX_SAME`)
    pub forex_yoy: Option<f64>,
    /// 国家外汇储备-环比 (Eastmoney `FOREX_SEQUENTIAL`)
    pub forex_mom: Option<f64>,
}

/// 东方财富-全国股票交易统计表 (`RPT_ECONOMY_STOCK_STATISTICS`, macro_china.py:2256).
#[derive(Debug, Clone, serde::Serialize)]
pub struct StockMarketCapRow {
    /// 数据日期 (Eastmoney `TIME`)
    pub date: String,
    /// 发行总股本-上海 (Eastmoney `TOTAL_SHARES_SH`)
    pub total_shares_sh: Option<f64>,
    /// 发行总股本-深圳 (Eastmoney `TOTAL_SZARES_SZ`)
    pub total_shares_sz: Option<f64>,
    /// 市价总值-上海 (Eastmoney `TOTAL_MARKE_SH`)
    pub market_cap_sh: Option<f64>,
    /// 市价总值-深圳 (Eastmoney `TOTAL_MARKE_SZ`)
    pub market_cap_sz: Option<f64>,
    /// 成交金额-上海 (Eastmoney `DEAL_AMOUNT_SH`)
    pub deal_amount_sh: Option<f64>,
    /// 成交金额-深圳 (Eastmoney `DEAL_AMOUNT_SZ`)
    pub deal_amount_sz: Option<f64>,
    /// 成交量-上海 (Eastmoney `VOLUME_SH`)
    pub volume_sh: Option<f64>,
    /// 成交量-深圳 (Eastmoney `VOLUME_SZ`)
    pub volume_sz: Option<f64>,
    /// A股最高综合股价指数-上海 (Eastmoney `HIGH_INDEX_SH`)
    pub high_index_sh: Option<f64>,
    /// A股最高综合股价指数-深圳 (Eastmoney `HIGH_INDEX_SZ`)
    pub high_index_sz: Option<f64>,
    /// A股最低综合股价指数-上海 (Eastmoney `LOW_INDEX_SH`)
    pub low_index_sh: Option<f64>,
    /// A股最低综合股价指数-深圳 (Eastmoney `LOW_INDEX_SZ`)
    pub low_index_sz: Option<f64>,
}

/// 东方财富-海关进出口增减情况一览表 (`RPT_ECONOMY_CUSTOMS`, macro_china.py:2723).
#[derive(Debug, Clone, serde::Serialize)]
pub struct HgjckRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 当月出口额-金额 (Eastmoney `EXIT_BASE`)
    pub export_current: Option<f64>,
    /// 当月出口额-同比增长 (Eastmoney `EXIT_BASE_SAME`)
    pub export_current_yoy: Option<f64>,
    /// 当月出口额-环比增长 (Eastmoney `EXIT_BASE_SEQUENTIAL`)
    pub export_current_mom: Option<f64>,
    /// 当月进口额-金额 (Eastmoney `IMPORT_BASE`)
    pub import_current: Option<f64>,
    /// 当月进口额-同比增长 (Eastmoney `IMPORT_BASE_SAME`)
    pub import_current_yoy: Option<f64>,
    /// 当月进口额-环比增长 (Eastmoney `IMPORT_BASE_SEQUENTIAL`)
    pub import_current_mom: Option<f64>,
    /// 累计出口额-金额 (Eastmoney `EXIT_ACCUMULATE`)
    pub export_accumulate: Option<f64>,
    /// 累计出口额-同比增长 (Eastmoney `EXIT_ACCUMULATE_SAME`)
    pub export_accumulate_yoy: Option<f64>,
    /// 累计进口额-金额 (Eastmoney `IMPORT_ACCUMULATE`)
    pub import_accumulate: Option<f64>,
    /// 累计进口额-同比增长 (Eastmoney `IMPORT_ACCUMULATE_SAME`)
    pub import_accumulate_yoy: Option<f64>,
}

/// 东方财富-财政收入 (`RPT_ECONOMY_INCOME`, macro_china.py:2814).
#[derive(Debug, Clone, serde::Serialize)]
pub struct CzsrRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 当月 (Eastmoney `BASE`)
    pub current: Option<f64>,
    /// 当月-同比增长 (Eastmoney `BASE_SAME`)
    pub current_yoy: Option<f64>,
    /// 当月-环比增长 (Eastmoney `BASE_SEQUENTIAL`)
    pub current_mom: Option<f64>,
    /// 累计 (Eastmoney `BASE_ACCUMULATE`)
    pub accumulate: Option<f64>,
    /// 累计-同比增长 (Eastmoney `ACCUMULATE_SAME`)
    pub accumulate_yoy: Option<f64>,
}

/// 东方财富-外汇贷款数据 (`RPT_ECONOMY_FOREX_LOAN`, macro_china.py:2867).
#[derive(Debug, Clone, serde::Serialize)]
pub struct WhxdRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 当月 (Eastmoney `BASE`)
    pub current: Option<f64>,
    /// 同比增长 (Eastmoney `BASE_SAME`)
    pub yoy: Option<f64>,
    /// 环比增长 (Eastmoney `BASE_SEQUENTIAL`)
    pub mom: Option<f64>,
    /// 累计 (Eastmoney `BASE_ACCUMULATE`)
    pub accumulate: Option<f64>,
}

/// 东方财富-本外币存款 (`RPT_ECONOMY_FOREX_DEPOSIT`, macro_china.py:2917).
#[derive(Debug, Clone, serde::Serialize)]
pub struct WbckRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 当月 (Eastmoney `BASE`)
    pub current: Option<f64>,
    /// 同比增长 (Eastmoney `BASE_SAME`)
    pub yoy: Option<f64>,
    /// 环比增长 (Eastmoney `BASE_SEQUENTIAL`)
    pub mom: Option<f64>,
    /// 累计 (Eastmoney `BASE_ACCUMULATE`)
    pub accumulate: Option<f64>,
}

/// 东方财富网-消费者信心指数 (`RPT_ECONOMY_FAITH_INDEX`, macro_china.py:2966).
#[derive(Debug, Clone, serde::Serialize)]
pub struct XfzxxRow {
    /// 月份 (Eastmoney `TIME`)
    pub month: String,
    /// 消费者信心指数-指数值 (Eastmoney `CONSUMERS_FAITH_INDEX`)
    pub faith_index: Option<f64>,
    /// 消费者信心指数-同比增长 (Eastmoney `FAITH_INDEX_SAME`)
    pub faith_yoy: Option<f64>,
    /// 消费者信心指数-环比增长 (Eastmoney `FAITH_INDEX_SEQUENTIAL`)
    pub faith_mom: Option<f64>,
    /// 消费者满意指数-指数值 (Eastmoney `CONSUMERS_ASTIS_INDEX`)
    pub satisfaction_index: Option<f64>,
    /// 消费者满意指数-同比增长 (Eastmoney `ASTIS_INDEX_SAME`)
    pub satisfaction_yoy: Option<f64>,
    /// 消费者满意指数-环比增长 (Eastmoney `ASTIS_INDEX_SEQUENTIAL`)
    pub satisfaction_mom: Option<f64>,
    /// 消费者预期指数-指数值 (Eastmoney `CONSUMERS_EXPECT_INDEX`)
    pub expectation_index: Option<f64>,
    /// 消费者预期指数-同比增长 (Eastmoney `EXPECT_INDEX_SAME`)
    pub expectation_yoy: Option<f64>,
    /// 消费者预期指数-环比增长 (Eastmoney `EXPECT_INDEX_SEQUENTIAL`)
    pub expectation_mom: Option<f64>,
}

/// 存款准备金率 (`RPT_ECONOMY_DEPOSIT_RESERVE`, macro_china.py:3096).
#[derive(Debug, Clone, serde::Serialize)]
pub struct ReserveRequirementRatioRow {
    /// 公布时间 (Eastmoney `PUBLISH_DATE`)
    pub publish_date: Option<String>,
    /// 生效时间 (Eastmoney `TRADE_DATE`)
    pub effective_date: Option<String>,
    /// 大型金融机构-调整前 (Eastmoney `INTEREST_RATE_BB`)
    pub big_before: Option<f64>,
    /// 大型金融机构-调整后 (Eastmoney `INTEREST_RATE_BA`)
    pub big_after: Option<f64>,
    /// 大型金融机构-调整幅度 (Eastmoney `CHANGE_RATE_B`)
    pub big_change: Option<f64>,
    /// 中小金融机构-调整前 (Eastmoney `INTEREST_RATE_SB`)
    pub small_before: Option<f64>,
    /// 中小金融机构-调整后 (Eastmoney `INTEREST_RATE_SA`)
    pub small_after: Option<f64>,
    /// 中小金融机构-调整幅度 (Eastmoney `CHANGE_RATE_S`)
    pub small_change: Option<f64>,
    /// 消息公布次日指数涨跌-上证 (Eastmoney `NEXT_SH_RATE`)
    pub next_sh: Option<f64>,
    /// 消息公布次日指数涨跌-深证 (Eastmoney `NEXT_SZ_RATE`)
    pub next_sz: Option<f64>,
    /// 备注 (Eastmoney `REMARK`)
    pub remark: Option<String>,
}

/// 中国新增信贷数据 (`macro_china_new_financial_credit`, Eastmoney `RPT_ECONOMY_RMB_LOAN`, macro_china.py:2142).
pub async fn macro_china_new_financial_credit(
    client: &Client,
) -> Result<Vec<NewFinancialCreditRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_new_financial_credit",
        "RPT_ECONOMY_RMB_LOAN",
        "REPORT_DATE,TIME,RMB_LOAN,RMB_LOAN_SAME,RMB_LOAN_SEQUENTIAL,RMB_LOAN_ACCUMULATE,LOAN_ACCUMULATE_SAME",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_new_financial_credit(&data)
}

/// 东方财富-外汇和黄金储备 (`macro_china_fx_gold`, Eastmoney `RPT_ECONOMY_GOLD_CURRENCY`, macro_china.py:2190).
pub async fn macro_china_fx_gold(client: &Client) -> Result<Vec<FxGoldRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_fx_gold",
        "RPT_ECONOMY_GOLD_CURRENCY",
        "REPORT_DATE,TIME,GOLD_RESERVES,GOLD_RESERVES_SAME,GOLD_RESERVES_SEQUENTIAL,FOREX,FOREX_SAME,FOREX_SEQUENTIAL",
        "1000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_fx_gold(&data)
}

/// 东方财富-全国股票交易统计表 (`macro_china_stock_market_cap`, Eastmoney `RPT_ECONOMY_STOCK_STATISTICS`, macro_china.py:2256).
pub async fn macro_china_stock_market_cap(client: &Client) -> Result<Vec<StockMarketCapRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_stock_market_cap",
        "RPT_ECONOMY_STOCK_STATISTICS",
        "REPORT_DATE,TIME,TOTAL_SHARES_SH,TOTAL_MARKE_SH,DEAL_AMOUNT_SH,VOLUME_SH,HIGH_INDEX_SH,LOW_INDEX_SH,TOTAL_SZARES_SZ,TOTAL_MARKE_SZ,DEAL_AMOUNT_SZ,VOLUME_SZ,HIGH_INDEX_SZ,LOW_INDEX_SZ",
        "1000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_stock_market_cap(&data)
}

/// 东方财富-海关进出口增减情况一览表 (`macro_china_hgjck`, Eastmoney `RPT_ECONOMY_CUSTOMS`, macro_china.py:2723).
pub async fn macro_china_hgjck(client: &Client) -> Result<Vec<HgjckRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_hgjck",
        "RPT_ECONOMY_CUSTOMS",
        "REPORT_DATE,TIME,EXIT_BASE,IMPORT_BASE,EXIT_BASE_SAME,IMPORT_BASE_SAME,EXIT_BASE_SEQUENTIAL,IMPORT_BASE_SEQUENTIAL,EXIT_ACCUMULATE,IMPORT_ACCUMULATE,EXIT_ACCUMULATE_SAME,IMPORT_ACCUMULATE_SAME",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_hgjck(&data)
}

/// 东方财富-财政收入 (`macro_china_czsr`, Eastmoney `RPT_ECONOMY_INCOME`, macro_china.py:2814).
pub async fn macro_china_czsr(client: &Client) -> Result<Vec<CzsrRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_czsr",
        "RPT_ECONOMY_INCOME",
        "REPORT_DATE,TIME,BASE,BASE_SAME,BASE_SEQUENTIAL,BASE_ACCUMULATE,ACCUMULATE_SAME",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_czsr(&data)
}

/// 东方财富-外汇贷款数据 (`macro_china_whxd`, Eastmoney `RPT_ECONOMY_FOREX_LOAN`, macro_china.py:2867).
pub async fn macro_china_whxd(client: &Client) -> Result<Vec<WhxdRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_whxd",
        "RPT_ECONOMY_FOREX_LOAN",
        "REPORT_DATE,TIME,BASE,BASE_SAME,BASE_SEQUENTIAL,BASE_ACCUMULATE",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_whxd(&data)
}

/// 东方财富-本外币存款 (`macro_china_wbck`, Eastmoney `RPT_ECONOMY_FOREX_DEPOSIT`, macro_china.py:2917).
pub async fn macro_china_wbck(client: &Client) -> Result<Vec<WbckRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_wbck",
        "RPT_ECONOMY_FOREX_DEPOSIT",
        "REPORT_DATE,TIME,BASE,BASE_SAME,BASE_SEQUENTIAL,BASE_ACCUMULATE",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_wbck(&data)
}

/// 东方财富网-消费者信心指数 (`macro_china_xfzxx`, Eastmoney `RPT_ECONOMY_FAITH_INDEX`, macro_china.py:2966).
pub async fn macro_china_xfzxx(client: &Client) -> Result<Vec<XfzxxRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_xfzxx",
        "RPT_ECONOMY_FAITH_INDEX",
        "REPORT_DATE,TIME,CONSUMERS_FAITH_INDEX,FAITH_INDEX_SAME,FAITH_INDEX_SEQUENTIAL,CONSUMERS_ASTIS_INDEX,ASTIS_INDEX_SAME,ASTIS_INDEX_SEQUENTIAL,CONSUMERS_EXPECT_INDEX,EXPECT_INDEX_SAME,EXPECT_INDEX_SEQUENTIAL",
        "2000",
        "REPORT_DATE",
        "-1",
        None,
    )
    .await?;
    parse_xfzxx(&data)
}

/// 存款准备金率 (`macro_china_reserve_requirement_ratio`, Eastmoney `RPT_ECONOMY_DEPOSIT_RESERVE`, macro_china.py:3096).
pub async fn macro_china_reserve_requirement_ratio(
    client: &Client,
) -> Result<Vec<ReserveRequirementRatioRow>> {
    let data = emdc_fetch(
        client,
        "macro_china_reserve_requirement_ratio",
        "RPT_ECONOMY_DEPOSIT_RESERVE",
        "REPORT_DATE,PUBLISH_DATE,TRADE_DATE,INTEREST_RATE_BB,INTEREST_RATE_BA,CHANGE_RATE_B,INTEREST_RATE_SB,INTEREST_RATE_SA,CHANGE_RATE_S,NEXT_SH_RATE,NEXT_SZ_RATE,REMARK",
        "2000",
        "PUBLISH_DATE,TRADE_DATE",
        "-1,-1",
        None,
    )
    .await?;
    parse_reserve_requirement_ratio(&data)
}

fn parse_new_financial_credit(items: &[Value]) -> Result<Vec<NewFinancialCreditRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(NewFinancialCreditRow {
            month,
            current: fnum(item, "RMB_LOAN"),
            current_yoy: fnum(item, "RMB_LOAN_SAME"),
            current_mom: fnum(item, "RMB_LOAN_SEQUENTIAL"),
            accumulate: fnum(item, "RMB_LOAN_ACCUMULATE"),
            accumulate_yoy: fnum(item, "LOAN_ACCUMULATE_SAME"),
        });
    }
    Ok(out)
}

fn parse_fx_gold(items: &[Value]) -> Result<Vec<FxGoldRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(FxGoldRow {
            month,
            gold_value: fnum(item, "GOLD_RESERVES"),
            gold_yoy: fnum(item, "GOLD_RESERVES_SAME"),
            gold_mom: fnum(item, "GOLD_RESERVES_SEQUENTIAL"),
            forex_value: fnum(item, "FOREX"),
            forex_yoy: fnum(item, "FOREX_SAME"),
            forex_mom: fnum(item, "FOREX_SEQUENTIAL"),
        });
    }
    Ok(out)
}

fn parse_stock_market_cap(items: &[Value]) -> Result<Vec<StockMarketCapRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(date) = fstr(item, "TIME") else {
            continue;
        };
        out.push(StockMarketCapRow {
            date,
            total_shares_sh: fnum(item, "TOTAL_SHARES_SH"),
            total_shares_sz: fnum(item, "TOTAL_SZARES_SZ"),
            market_cap_sh: fnum(item, "TOTAL_MARKE_SH"),
            market_cap_sz: fnum(item, "TOTAL_MARKE_SZ"),
            deal_amount_sh: fnum(item, "DEAL_AMOUNT_SH"),
            deal_amount_sz: fnum(item, "DEAL_AMOUNT_SZ"),
            volume_sh: fnum(item, "VOLUME_SH"),
            volume_sz: fnum(item, "VOLUME_SZ"),
            high_index_sh: fnum(item, "HIGH_INDEX_SH"),
            high_index_sz: fnum(item, "HIGH_INDEX_SZ"),
            low_index_sh: fnum(item, "LOW_INDEX_SH"),
            low_index_sz: fnum(item, "LOW_INDEX_SZ"),
        });
    }
    Ok(out)
}

fn parse_hgjck(items: &[Value]) -> Result<Vec<HgjckRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(HgjckRow {
            month,
            export_current: fnum(item, "EXIT_BASE"),
            export_current_yoy: fnum(item, "EXIT_BASE_SAME"),
            export_current_mom: fnum(item, "EXIT_BASE_SEQUENTIAL"),
            import_current: fnum(item, "IMPORT_BASE"),
            import_current_yoy: fnum(item, "IMPORT_BASE_SAME"),
            import_current_mom: fnum(item, "IMPORT_BASE_SEQUENTIAL"),
            export_accumulate: fnum(item, "EXIT_ACCUMULATE"),
            export_accumulate_yoy: fnum(item, "EXIT_ACCUMULATE_SAME"),
            import_accumulate: fnum(item, "IMPORT_ACCUMULATE"),
            import_accumulate_yoy: fnum(item, "IMPORT_ACCUMULATE_SAME"),
        });
    }
    Ok(out)
}

fn parse_czsr(items: &[Value]) -> Result<Vec<CzsrRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(CzsrRow {
            month,
            current: fnum(item, "BASE"),
            current_yoy: fnum(item, "BASE_SAME"),
            current_mom: fnum(item, "BASE_SEQUENTIAL"),
            accumulate: fnum(item, "BASE_ACCUMULATE"),
            accumulate_yoy: fnum(item, "ACCUMULATE_SAME"),
        });
    }
    Ok(out)
}

fn parse_whxd(items: &[Value]) -> Result<Vec<WhxdRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(WhxdRow {
            month,
            current: fnum(item, "BASE"),
            yoy: fnum(item, "BASE_SAME"),
            mom: fnum(item, "BASE_SEQUENTIAL"),
            accumulate: fnum(item, "BASE_ACCUMULATE"),
        });
    }
    Ok(out)
}

fn parse_wbck(items: &[Value]) -> Result<Vec<WbckRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(WbckRow {
            month,
            current: fnum(item, "BASE"),
            yoy: fnum(item, "BASE_SAME"),
            mom: fnum(item, "BASE_SEQUENTIAL"),
            accumulate: fnum(item, "BASE_ACCUMULATE"),
        });
    }
    Ok(out)
}

fn parse_xfzxx(items: &[Value]) -> Result<Vec<XfzxxRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let Some(month) = fstr(item, "TIME") else {
            continue;
        };
        out.push(XfzxxRow {
            month,
            faith_index: fnum(item, "CONSUMERS_FAITH_INDEX"),
            faith_yoy: fnum(item, "FAITH_INDEX_SAME"),
            faith_mom: fnum(item, "FAITH_INDEX_SEQUENTIAL"),
            satisfaction_index: fnum(item, "CONSUMERS_ASTIS_INDEX"),
            satisfaction_yoy: fnum(item, "ASTIS_INDEX_SAME"),
            satisfaction_mom: fnum(item, "ASTIS_INDEX_SEQUENTIAL"),
            expectation_index: fnum(item, "CONSUMERS_EXPECT_INDEX"),
            expectation_yoy: fnum(item, "EXPECT_INDEX_SAME"),
            expectation_mom: fnum(item, "EXPECT_INDEX_SEQUENTIAL"),
        });
    }
    Ok(out)
}

fn parse_reserve_requirement_ratio(items: &[Value]) -> Result<Vec<ReserveRequirementRatioRow>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        out.push(ReserveRequirementRatioRow {
            publish_date: fstr(item, "PUBLISH_DATE"),
            effective_date: fstr(item, "TRADE_DATE"),
            big_before: fnum(item, "INTEREST_RATE_BB"),
            big_after: fnum(item, "INTEREST_RATE_BA"),
            big_change: fnum(item, "CHANGE_RATE_B"),
            small_before: fnum(item, "INTEREST_RATE_SB"),
            small_after: fnum(item, "INTEREST_RATE_SA"),
            small_change: fnum(item, "CHANGE_RATE_S"),
            next_sh: fnum(item, "NEXT_SH_RATE"),
            next_sz: fnum(item, "NEXT_SZ_RATE"),
            remark: fstr(item, "REMARK"),
        });
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture(name: &str) -> Value {
        let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name);
        serde_json::from_str(&std::fs::read_to_string(p).unwrap()).unwrap()
    }

    /// Extract the `result.data` array from a fixture response.
    fn data_of(name: &str) -> Vec<Value> {
        emg_data_array(&fixture(name)).unwrap().clone()
    }

    /// Parse a Group-A (RPT_INDUSTRY_INDEX) fixture.
    fn industry_rows(name: &str) -> Vec<IndustryIndexRow> {
        parse_industry_index(&data_of(name)).unwrap()
    }

    // ---- Group A: RPT_INDUSTRY_INDEX ----

    #[test]
    fn parses_macro_china_bank_financing() {
        let rows = industry_rows("macro_china_bank_financing.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_rate, Some(1.2));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].date, "2024-02-15");
        assert_eq!(rows[1].latest_value, Some(1200.0));
        assert_eq!(rows[1].change_3y, Some(6.7));
    }

    #[test]
    fn parses_macro_china_insurance_income() {
        let rows = industry_rows("macro_china_insurance_income.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_mobile_number() {
        let rows = industry_rows("macro_china_mobile_number.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_vegetable_basket() {
        let rows = industry_rows("macro_china_vegetable_basket.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_agricultural_product() {
        let rows = industry_rows("macro_china_agricultural_product.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_agricultural_index() {
        let rows = industry_rows("macro_china_agricultural_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_energy_index() {
        let rows = industry_rows("macro_china_energy_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_commodity_price_index() {
        let rows = industry_rows("macro_china_commodity_price_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_global_sox_index() {
        let rows = industry_rows("macro_global_sox_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_yw_electronic_index() {
        let rows = industry_rows("macro_china_yw_electronic_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_construction_index() {
        let rows = industry_rows("macro_china_construction_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_construction_price_index() {
        let rows = industry_rows("macro_china_construction_price_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_lpi_index() {
        let rows = industry_rows("macro_china_lpi_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_bdti_index() {
        let rows = industry_rows("macro_china_bdti_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_bsi_index() {
        let rows = industry_rows("macro_china_bsi_index.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    #[test]
    fn parses_macro_china_real_estate() {
        let rows = industry_rows("macro_china_real_estate.json");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].latest_value, Some(1234.5));
        assert_eq!(rows[0].change_3y, None);
        assert_eq!(rows[1].latest_value, Some(1200.0));
    }

    // ---- Group B: RPT_ECONOMY_* ----

    #[test]
    fn parses_macro_china_new_financial_credit() {
        let rows =
            parse_new_financial_credit(&data_of("macro_china_new_financial_credit.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].current, Some(12000.5));
        assert_eq!(rows[0].current_mom, None);
        assert_eq!(rows[0].accumulate, Some(35000.0));
        assert_eq!(rows[1].current, Some(11000.0));
        assert_eq!(rows[1].current_mom, Some(1.0));
    }

    #[test]
    fn parses_macro_china_fx_gold() {
        let rows = parse_fx_gold(&data_of("macro_china_fx_gold.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].gold_value, Some(2264.0));
        assert_eq!(rows[0].forex_mom, None);
        assert_eq!(rows[1].forex_mom, Some(1.2));
    }

    #[test]
    fn parses_macro_china_stock_market_cap() {
        let rows = parse_stock_market_cap(&data_of("macro_china_stock_market_cap.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].date, "2024-03-15");
        assert_eq!(rows[0].market_cap_sh, Some(45000.0));
        assert_eq!(rows[0].low_index_sz, None);
        assert_eq!(rows[1].low_index_sz, Some(1000.0));
    }

    #[test]
    fn parses_macro_china_hgjck() {
        let rows = parse_hgjck(&data_of("macro_china_hgjck.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].export_current, Some(3000.0));
        assert_eq!(rows[0].import_accumulate_yoy, None);
        assert_eq!(rows[1].import_accumulate_yoy, Some(5.5));
    }

    #[test]
    fn parses_macro_china_czsr() {
        let rows = parse_czsr(&data_of("macro_china_czsr.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].current, Some(20000.0));
        assert_eq!(rows[0].current_mom, None);
        assert_eq!(rows[1].current_mom, Some(1.5));
    }

    #[test]
    fn parses_macro_china_whxd() {
        let rows = parse_whxd(&data_of("macro_china_whxd.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].current, Some(8000.0));
        assert_eq!(rows[0].mom, None);
        assert_eq!(rows[1].mom, Some(0.5));
    }

    #[test]
    fn parses_macro_china_wbck() {
        let rows = parse_wbck(&data_of("macro_china_wbck.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].current, Some(150000.0));
        assert_eq!(rows[0].yoy, None);
        assert_eq!(rows[1].yoy, Some(3.0));
    }

    #[test]
    fn parses_macro_china_xfzxx() {
        let rows = parse_xfzxx(&data_of("macro_china_xfzxx.json")).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].month, "2024年03月");
        assert_eq!(rows[0].faith_index, Some(110.0));
        assert_eq!(rows[0].expectation_index, None);
        assert_eq!(rows[1].expectation_index, Some(112.0));
    }

    #[test]
    fn parses_macro_china_reserve_requirement_ratio() {
        let rows =
            parse_reserve_requirement_ratio(&data_of("macro_china_reserve_requirement_ratio.json"))
                .unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].publish_date, Some("2024-03-01".to_string()));
        assert_eq!(rows[0].effective_date, Some("2024-03-15".to_string()));
        assert_eq!(rows[0].big_after, Some(10.0));
        assert_eq!(rows[0].remark, None);
        assert_eq!(rows[1].remark, Some("定向降准".to_string()));
    }
}
